## NLP
### Encoding Techniques
We cannot directly feed our text into that algorithm.So some of word Embedding techniques that we need to apply on it before training and testing:

*Bag of words
*N-grams
*TF-IDF vectorizer

Some common terms to remember:
1. Corpus
2. Vocabulary
3. Document
4. Word

# Bag of words

In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.DataFrame({"text":["people watch data_discovery",
                         "data_discovery speaks about data",
                         "people write comment",
                          "data_discovery write comment"],"output":[1,1,0,0]})

df

text  output
0       people watch data_discovery       1
1  data_discovery speaks about data       1
2              people write comment       0
3      data_discovery write comment       0

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [5]:
bow = cv.fit_transform(df['text'])

In [6]:
#vocabulary
print(cv.vocabulary_)

{'people': 4, 'watch': 6, 'data_discovery': 3, 'speaks': 5, 'about': 0, 'data': 2, 'write': 7, 'comment': 1}


In [7]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 0 0 1 1 0 1 0]]
[[1 0 1 1 0 1 0 0]]
[[0 1 0 0 1 0 0 1]]


In [8]:
# new
cv.transform(['Bappy watch dswithbappy']).toarray()

array([[0, 0, 0, 0, 0, 0, 1, 0]], dtype=int64)

In [9]:
X = bow.toarray()
y = df['output']

In [10]:
y

0    1
1    1
2    0
3    0
Name: output, dtype: int64

#  N-grams

In [11]:
df = pd.DataFrame({"text":["people watch data_discovery",
                         "data_discovery speaks about data",
                         "people write comment",
                          "data_discovery write comment"],"output":[1,1,0,0]})

df

text  output
0       people watch data_discovery       1
1  data_discovery speaks about data       1
2              people write comment       0
3      data_discovery write comment       0

In [12]:
# BI grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(2,2))

In [13]:
bow = cv.fit_transform(df['text'])

In [14]:
print(cv.vocabulary_)

{'people watch': 3, 'watch data_discovery': 6, 'data_discovery speaks': 1, 'speaks about': 5, 'about data': 0, 'people write': 4, 'write comment': 7, 'data_discovery write': 2}


In [15]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 0 0 1 0 0 1 0]]
[[1 1 0 0 0 1 0 0]]
[[0 0 0 0 1 0 0 1]]


In [16]:
#Ti gram
# BI grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(3,3))

In [17]:
bow = cv.fit_transform(df['text'])

In [18]:
print(cv.vocabulary_)

{'people watch data_discovery': 2, 'data_discovery speaks about': 0, 'speaks about data': 4, 'people write comment': 3, 'data_discovery write comment': 1}


In [19]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 0 1 0 0]]
[[1 0 0 0 1]]
[[0 0 0 1 0]]


# TF-IDF (Term frequency- Inverse document frequency)

In [20]:
df = pd.DataFrame({"text":["people watch data_discovery",
                         "data_discovery speaks about data",
                         "people write comment",
                          "data_discovery write comment"],"output":[1,1,0,0]})

df

text  output
0       people watch data_discovery       1
1  data_discovery speaks about data       1
2              people write comment       0
3      data_discovery write comment       0

In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfid= TfidfVectorizer()

In [22]:
tfid.fit_transform(df['text']).toarray()

array([[0.        , 0.        , 0.        , 0.44809973, 0.55349232,
        0.        , 0.70203482, 0.        ],
       [0.5417361 , 0.        , 0.5417361 , 0.34578314, 0.        ,
        0.5417361 , 0.        , 0.        ],
       [0.        , 0.57735027, 0.        , 0.        , 0.57735027,
        0.        , 0.        , 0.57735027],
       [0.        , 0.61366674, 0.        , 0.49681612, 0.        ,
        0.        , 0.        , 0.61366674]])

In [23]:
print(tfid.idf_)

[1.91629073 1.51082562 1.91629073 1.22314355 1.51082562 1.91629073
 1.91629073 1.51082562]
